import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const CONFIG = "onerule.json";
export const MARK = "<!-- onerule: generated from";

export type Target = { id: string; tool: string; file: string; pointer?: (source: string) => string };
export type Config = { source: string; targets: string[] };
export type State = "ok" | "missing" | "drifted" | "conflict";
export type Plan = { target: Target; state: State; content: string; note: string };

export const TARGETS: Target[] = [
  { id: "agents", tool: "Codex, Cursor, Copilot agents, others", file: "AGENTS.md" },
  { id: "claude", tool: "Claude Code", file: "CLAUDE.md", pointer: (s) => `@${s}` },
  { id: "gemini", tool: "Gemini CLI", file: "GEMINI.md", pointer: (s) => `@./${s}` },
  { id: "cursor", tool: "Cursor", file: ".cursor/rules/onerule.mdc" },
  { id: "copilot", tool: "GitHub Copilot", file: ".github/copilot-instructions.md" },
];

const ROOT_FILES = ["AGENTS.md", "CLAUDE.md", "GEMINI.md", ".github/copilot-instructions.md"];

export const lf = (s: string) => s.replace(/^﻿/, "").replace(/\r\n/g, "\n");

const linesOf = (s: string) => s.split("\n").map((l) => l.trim()).filter(Boolean);

function covered(text: string, body: string): boolean {
  const have = new Set(linesOf(text));
  return linesOf(body).every((l) => have.has(l));
}

export function read(root: string, file: string): string | undefined {
  const path = join(root, file);
  return existsSync(path) ? lf(readFileSync(path, "utf8")) : undefined;
}

function write(root: string, file: string, text: string) {
  const path = join(root, file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
}

export function getTarget(id: string): Target {
  const t = TARGETS.find((t) => t.id === id);
  if (!t) throw new Error(`unknown target "${id}". Known: ${TARGETS.map((t) => t.id).join(", ")}`);
  return t;
}

export function defaultTargets(root: string, source: string): string[] {
  const cursor = source !== "AGENTS.md" && existsSync(join(root, ".cursor"));
  return TARGETS.filter((t) => t.file !== source && (t.id !== "cursor" || cursor)).map((t) => t.id);
}

export function loadConfig(root: string): Config {
  const raw = read(root, CONFIG);
  if (raw === undefined) return { source: "AGENTS.md", targets: defaultTargets(root, "AGENTS.md") };
  let parsed: Partial<Config>;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new Error(`${CONFIG}: ${(e as Error).message}`);
  }
  const source = parsed.source ?? "AGENTS.md";
  const targets = parsed.targets ?? defaultTargets(root, source);
  if (typeof source !== "string" || !Array.isArray(targets)) throw new Error(`${CONFIG}: "source" must be a string and "targets" an array`);
  for (const id of targets) if (getTarget(id).file === source) throw new Error(`${CONFIG}: target "${id}" is the source file`);
  return { source, targets };
}

export function render(target: Target, source: string, text: string): string {
  if (target.pointer) return `${target.pointer(source)}\n`;
  const header = `${MARK} ${source}. Edit ${source}, then run: npx onerule sync --apply -->`;
  const body = `${header}\n\n${text.trimEnd()}\n`;
  if (!target.file.endsWith(".mdc")) return body;
  return `---\ndescription: Project instructions from ${source}\nalwaysApply: true\n---\n${body}`;
}

function planOne(root: string, target: Target, source: string, text: string): Plan {
  const want = render(target, source, text);
  const have = read(root, target.file);
  if (have === undefined) return { target, state: "missing", content: want, note: "" };
  if (target.pointer) {
    const line = target.pointer(source);
    if (have.split("\n").some((l) => l.trim() === line)) return { target, state: "ok", content: have, note: `imports ${source}` };
    const body = have.trim();
    if (!body || body.includes(MARK) || covered(text, body)) return { target, state: "drifted", content: want, note: `content already in ${source}, replace with ${line}` };
    return { target, state: "drifted", content: `${line}\n\n${have}`, note: `add ${line}, keep existing content` };
  }
  if (have === want) return { target, state: "ok", content: have, note: `copy of ${source}` };
  if (have.includes(MARK)) return { target, state: "drifted", content: want, note: `stale copy of ${source}` };
  return { target, state: "conflict", content: want, note: "hand-written, not generated by onerule (--force to overwrite)" };
}

export function plan(root: string, config: Config = loadConfig(root), text = read(root, config.source)): Plan[] {
  if (text === undefined) throw new Error(`source ${config.source} not found. Run: npx onerule init`);
  return config.targets.map((id) => planOne(root, getTarget(id), config.source, text));
}

export function apply(root: string, plans: Plan[], force = false) {
  for (const p of plans) {
    if (p.state === "ok" || (p.state === "conflict" && !force)) continue;
    rmSync(join(root, p.target.file), { force: true });
    write(root, p.target.file, p.content);
  }
}

export type Init = { config: Config; text: string; created: boolean; merged: string[] };

export function init(root: string, source = "AGENTS.md", targets?: string[]): Init {
  const pointers = TARGETS.flatMap((t) => (t.pointer ? [t.pointer(source)] : []));
  const existing = read(root, source);
  let text = existing ?? "";
  const merged: string[] = [];
  for (const file of ROOT_FILES) {
    const raw = file === source ? undefined : read(root, file);
    if (raw === undefined || raw.includes(MARK)) continue;
    const body = raw.split("\n").filter((l) => !pointers.includes(l.trim())).join("\n").trim();
    merged.push(file);
    if (!body || covered(text, body)) continue;
    text = text.trim() ? `${text.trimEnd()}\n\n## From ${file}\n\n${body}\n` : `${body}\n`;
  }
  if (!text.trim()) text = "# Agent instructions\n\nBuild, test and style rules for coding agents working in this repo.\n";
  const config = { source, targets: targets ?? defaultTargets(root, source) };
  for (const id of config.targets) if (getTarget(id).file === source) throw new Error(`target "${id}" is the source file`);
  return { config, text, created: existing === undefined, merged };
}

export function initPlans(root: string, result: Init): Plan[] {
  return plan(root, result.config, result.text).map((p) =>
    p.state === "conflict" && result.merged.includes(p.target.file) ? { ...p, state: "drifted", note: `merged into ${result.config.source}` } : p,
  );
}

export function writeInit(root: string, result: Init, plans: Plan[]) {
  write(root, result.config.source, result.text);
  write(root, CONFIG, `${JSON.stringify(result.config, null, 2)}\n`);
  apply(root, plans);
}
